ENDPOINT = 'https://rest.coinapi.io/v1'
API_KEY = ''
API_TOKEN = ''
TOP_CURRENCIES_LIST = ['BTC', 'ETH', 'USDT', 'BNB', 'USDC', 'XRP']
CURRENCIES_LIST = []
LOCAL_STORAGE = {}
DEFAULT_EXCHANGE = 'RUB'
